/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: devteroflex.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "qflex/devteroflex/devteroflex.pb-c.h"
void   devteroflex_arch_state_p__init
                     (DevteroflexArchStateP         *message)
{
  static const DevteroflexArchStateP init_value = DEVTEROFLEX_ARCH_STATE_P__INIT;
  *message = init_value;
}
size_t devteroflex_arch_state_p__get_packed_size
                     (const DevteroflexArchStateP *message)
{
  assert(message->base.descriptor == &devteroflex_arch_state_p__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t devteroflex_arch_state_p__pack
                     (const DevteroflexArchStateP *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &devteroflex_arch_state_p__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t devteroflex_arch_state_p__pack_to_buffer
                     (const DevteroflexArchStateP *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &devteroflex_arch_state_p__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DevteroflexArchStateP *
       devteroflex_arch_state_p__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DevteroflexArchStateP *)
     protobuf_c_message_unpack (&devteroflex_arch_state_p__descriptor,
                                allocator, len, data);
}
void   devteroflex_arch_state_p__free_unpacked
                     (DevteroflexArchStateP *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &devteroflex_arch_state_p__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   devteroflex_commit_trace_p__init
                     (DevteroflexCommitTraceP         *message)
{
  static const DevteroflexCommitTraceP init_value = DEVTEROFLEX_COMMIT_TRACE_P__INIT;
  *message = init_value;
}
size_t devteroflex_commit_trace_p__get_packed_size
                     (const DevteroflexCommitTraceP *message)
{
  assert(message->base.descriptor == &devteroflex_commit_trace_p__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t devteroflex_commit_trace_p__pack
                     (const DevteroflexCommitTraceP *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &devteroflex_commit_trace_p__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t devteroflex_commit_trace_p__pack_to_buffer
                     (const DevteroflexCommitTraceP *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &devteroflex_commit_trace_p__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DevteroflexCommitTraceP *
       devteroflex_commit_trace_p__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DevteroflexCommitTraceP *)
     protobuf_c_message_unpack (&devteroflex_commit_trace_p__descriptor,
                                allocator, len, data);
}
void   devteroflex_commit_trace_p__free_unpacked
                     (DevteroflexCommitTraceP *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &devteroflex_commit_trace_p__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor devteroflex_arch_state_p__field_descriptors[4] =
{
  {
    "xregs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(DevteroflexArchStateP, n_xregs),
    offsetof(DevteroflexArchStateP, xregs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pc",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DevteroflexArchStateP, pc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DevteroflexArchStateP, sp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nzcv",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DevteroflexArchStateP, nzcv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned devteroflex_arch_state_p__field_indices_by_name[] = {
  3,   /* field[3] = nzcv */
  1,   /* field[1] = pc */
  2,   /* field[2] = sp */
  0,   /* field[0] = xregs */
};
static const ProtobufCIntRange devteroflex_arch_state_p__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor devteroflex_arch_state_p__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DevteroflexArchState_p",
  "DevteroflexArchStateP",
  "DevteroflexArchStateP",
  "",
  sizeof(DevteroflexArchStateP),
  4,
  devteroflex_arch_state_p__field_descriptors,
  devteroflex_arch_state_p__field_indices_by_name,
  1,  devteroflex_arch_state_p__number_ranges,
  (ProtobufCMessageInit) devteroflex_arch_state_p__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor devteroflex_commit_trace_p__field_descriptors[6] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DevteroflexCommitTraceP, state),
    &devteroflex_arch_state_p__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inst",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DevteroflexCommitTraceP, inst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_addr",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(DevteroflexCommitTraceP, n_mem_addr),
    offsetof(DevteroflexCommitTraceP, mem_addr),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_data",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(DevteroflexCommitTraceP, n_mem_data),
    offsetof(DevteroflexCommitTraceP, mem_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inst_block_data",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DevteroflexCommitTraceP, inst_block_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_block_data",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(DevteroflexCommitTraceP, n_mem_block_data),
    offsetof(DevteroflexCommitTraceP, mem_block_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned devteroflex_commit_trace_p__field_indices_by_name[] = {
  1,   /* field[1] = inst */
  4,   /* field[4] = inst_block_data */
  2,   /* field[2] = mem_addr */
  5,   /* field[5] = mem_block_data */
  3,   /* field[3] = mem_data */
  0,   /* field[0] = state */
};
static const ProtobufCIntRange devteroflex_commit_trace_p__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor devteroflex_commit_trace_p__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DevteroflexCommitTrace_p",
  "DevteroflexCommitTraceP",
  "DevteroflexCommitTraceP",
  "",
  sizeof(DevteroflexCommitTraceP),
  6,
  devteroflex_commit_trace_p__field_descriptors,
  devteroflex_commit_trace_p__field_indices_by_name,
  1,  devteroflex_commit_trace_p__number_ranges,
  (ProtobufCMessageInit) devteroflex_commit_trace_p__init,
  NULL,NULL,NULL    /* reserved[123] */
};
